baseURL = "http://camilogarcialarotta.github.io/"
languageCode = "en-us"
title = "Personal Site"
publishDir = "camilogarcialarotta.github.io"

[permalinks]
blog = "/:filename/"

[params]
dateFormat = "Jan 2, 2006"
author = "Camilo Garcia La Rotta"
position = "Software Engineering Undergrad"

[taxonomies]
tag = "tags"
