baseURL = "http://camilogarcialarotta.github.io/"
languageCode = "en-us"
title = "Personal Site"
publishDir = "camilogarcialarotta.github.io"

[permalinks]
blog = "/blog/:filename/"
kivu = "/kivu/:filename/"

[params]
dateFormat = "Jan 2, 2006"
author = "Camilo Garcia La Rotta"
motto = "Go, Ruby, Typescript and cheap poetry"

[taxonomies]
tag = "tags"
